# Generated by Django 2.2 on 2022-03-11 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tess', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog',
            new_name='myblog',
        ),
    ]
