# Generated by Django 2.2 on 2022-03-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tess', '0003_auto_20220311_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='title',
            new_name='caption',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='body',
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.FileField(upload_to='img/%y'),
        ),
    ]
