# Generated by Django 2.2 on 2022-03-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tess', '0005_prove'),
    ]

    operations = [
        migrations.CreateModel(
            name='grate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='img/%y')),
            ],
        ),
    ]
