# Generated by Django 2.2 on 2022-03-22 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tess', '0006_grate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blog',
        ),
    ]
