# Generated by Django 2.2 on 2022-03-31 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tess', '0007_delete_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('main_news', models.CharField(max_length=200)),
            ],
        ),
    ]
