# Generated by Django 2.2 on 2022-03-31 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tess', '0008_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='main_news',
            field=models.CharField(max_length=400),
        ),
    ]
