# Generated by Django 2.2 on 2022-03-31 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tess', '0009_auto_20220331_0637'),
    ]

    operations = [
        migrations.CreateModel(
            name='hmm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('hes', models.CharField(max_length=200)),
                ('main_news', models.CharField(max_length=400)),
            ],
        ),
        migrations.DeleteModel(
            name='news',
        ),
    ]
